// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvRdVuLUnDEi7DPxn1ESQhXD0PY6-oqY',
    appId: '1:823007096408:web:f5d57b7a35c46efe3a242d',
    messagingSenderId: '823007096408',
    projectId: 'edco-envymusic',
    authDomain: 'edco-envymusic.firebaseapp.com',
    databaseURL: 'https://edco-envymusic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edco-envymusic.appspot.com',
    measurementId: 'G-R8V24THEN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDne7mRv8p2erhl9Ssz2D_0KSwXbt3AcuQ',
    appId: '1:823007096408:android:075ea5d703b737d23a242d',
    messagingSenderId: '823007096408',
    projectId: 'edco-envymusic',
    databaseURL: 'https://edco-envymusic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edco-envymusic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0uXclCodLhpVExQBRmm3KyGJuAy0Uww',
    appId: '1:823007096408:ios:cbd697e5567095493a242d',
    messagingSenderId: '823007096408',
    projectId: 'edco-envymusic',
    databaseURL: 'https://edco-envymusic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edco-envymusic.appspot.com',
    iosClientId: '823007096408-nlnucsp311h5utcgn6mcfsc6hg4qhfeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi0uXclCodLhpVExQBRmm3KyGJuAy0Uww',
    appId: '1:823007096408:ios:cbd697e5567095493a242d',
    messagingSenderId: '823007096408',
    projectId: 'edco-envymusic',
    databaseURL: 'https://edco-envymusic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edco-envymusic.appspot.com',
    iosClientId: '823007096408-nlnucsp311h5utcgn6mcfsc6hg4qhfeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicplayer',
  );
}
